#!/usr/bin/php
<?php

/**
 * Swift
 *
 * @author    Swift dev team
 * @copyright Copyright (c) 2010, Swift dev team
 * @license   LICENSE
 * @package   Swift
 */

define('ENV', 'development');
define("ROOT_DIR", getcwd() . '/../');
define("LIB_DIR", ROOT_DIR . "lib/");
define("DIR", ROOT_DIR . "tests/fixtures/");

include LIB_DIR . "boot.php";

?>
