#!/usr/bin/php
<?php

/**
 * Swift
 *
 * @author    Swift dev team
 * @copyright Copyright (c) 2010, Swift dev team
 * @license   LICENSE
 * @package   Swift
 */

define('ENV', 'development');
define("ROOT_DIR", getcwd() . '/');
define("LIB_DIR", ROOT_DIR . "swift/lib/");
define("DIR", ROOT_DIR);

include LIB_DIR . "base.php";
include LIB_DIR . "dir.php";
include LIB_DIR . "constants.php";
include LIB_DIR . "helpers.php";
include LIB_DIR . "app.php";
spl_autoload_register('App::load'); // tmp
App::load('scripts');

$scripts = new Scripts();
$scripts -> call(array_slice($argv, 1));

?>
